CREATE TABLE matches
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fixture_id BIGINT,
    league     VARCHAR(255),
    home_team  VARCHAR(255),
    away_team  VARCHAR(255),
    home_score INTEGER                                 NOT NULL,
    away_score INTEGER                                 NOT NULL,
    time       VARCHAR(255),
    CONSTRAINT pk_matches PRIMARY KEY (id)
);

ALTER TABLE matches
    ADD CONSTRAINT uc_matches_fixtureid UNIQUE (fixture_id);