CREATE TABLE tournament
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    start_date  date,
    end_date    date,
    CONSTRAINT pk_tournament PRIMARY KEY (id)
);