CREATE TABLE team (
                      id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                      name VARCHAR(255),
                      CONSTRAINT pk_team PRIMARY KEY (id)
);

CREATE TABLE player (
                        id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        name     VARCHAR(255),
                        position VARCHAR(255),
                        team_id  BIGINT,
                        CONSTRAINT pk_player PRIMARY KEY (id)
);

CREATE TABLE tournament_match (
                                  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  team1_id      BIGINT,
                                  team2_id      BIGINT,
                                  team1score    INTEGER NOT NULL,
                                  team2score    INTEGER NOT NULL,
                                  status        VARCHAR(255),
                                  tournament_id BIGINT,
                                  CONSTRAINT pk_tournamentmatch PRIMARY KEY (id)
);

ALTER TABLE player
    ADD CONSTRAINT FK_PLAYER_ON_TEAM FOREIGN KEY (team_id) REFERENCES team (id);

ALTER TABLE tournament_match
    ADD CONSTRAINT FK_TOURNAMENTMATCH_ON_TEAM1 FOREIGN KEY (team1_id) REFERENCES team (id);

ALTER TABLE tournament_match
    ADD CONSTRAINT FK_TOURNAMENTMATCH_ON_TEAM2 FOREIGN KEY (team2_id) REFERENCES team (id);

ALTER TABLE tournament_match
    ADD CONSTRAINT FK_TOURNAMENTMATCH_ON_TOURNAMENT FOREIGN KEY (tournament_id) REFERENCES tournament (id);
